server:
  port: 6001

spring:
  profiles: default
  datasource:
    url: jdbc:mysql://localhost:3306/UserInformation
    username: root
    password: root
    useSSL: false
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
      show-sql: true
      useSSL: false
      naming-strategy: org.hibernate.cfg.ImprovedNamingStrategy
      dialect: org.hibernate.dialect.MySQL8Dialect
